# Development Configuration
server.port=8080
logging.level.com.events_cav=DEBUG
spring.doc.swagger-ui.enabled=true

# --- JWT Configuration ---
#jwt.secret-key=militaseeee*militaseeee*militaseeee*
jwt.secret-key=Rk9SVEFMRUNJTU9fQ0xPVkVfU0VDUkVUQV9MQUdSXzI1Ng==
jwt.expiration=86400000