spring.application.name=events-venues
# Le decimos a Spring que arranque por defecto en modo DEV
spring.profiles.active=dev

# Configuración DB -> H2
spring.datasource.url=jdbc:h2:mem:eventsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=militaseeee
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Seguridad (Ocultar errores)
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=always
server.error.include-binding-errors=never

# SWAGGER (Rutas base)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html