spring.application.name=events-venues
spring.profiles.active=dev

# Security error management
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=always
server.error.include-binding-errors=never